[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.28.1"
egui = "0.28.1"
tokio = { version = "1.0.0", features = ["full"]}
mini-redis = "0.4.1"
shared = {path = "../shared"}
serde = {version = "1.0.204", features = ["derive"]}
bincode = "1.3.3"
rand = "0.8.5"